/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pchecker;

/**
 *
 * @author Pawel Szymczyk
 */
public class LogInForm extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    public LogInForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameInput = new javax.swing.JTextField();
        PasswordInput = new javax.swing.JTextField();
        forgotPswLink = new javax.swing.JLabel();
        createAccountLink = new javax.swing.JLabel();
        RegistrationPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        confirmField = new javax.swing.JTextField();
        forenameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ForgotPasswordPanel = new javax.swing.JPanel();
        informLabelFP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameLabelFP = new javax.swing.JLabel();
        emailLabelFP = new javax.swing.JLabel();
        usernameFieldFP = new javax.swing.JTextField();
        emailFieldFP = new javax.swing.JTextField();
        acceptBtnFP = new javax.swing.JButton();
        cancelBtnFP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ComPChecker");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        LogInPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogInPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        LogInPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        LogInPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        LogInPanel.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pchecker/logo.png"))); // NOI18N
        LogInPanel.add(logo);
        logo.setBounds(140, 150, 602, 119);

        loginBtn.setText("Login");
        LogInPanel.add(loginBtn);
        loginBtn.setBounds(377, 421, 57, 45);

        exitBtn.setText("Exit");
        LogInPanel.add(exitBtn);
        exitBtn.setBounds(473, 421, 57, 45);

        UserNameLabel.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        UserNameLabel.setText("Username:");
        LogInPanel.add(UserNameLabel);
        UserNameLabel.setBounds(240, 340, 76, 19);

        PasswordLabel.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        PasswordLabel.setText("Password:");
        LogInPanel.add(PasswordLabel);
        PasswordLabel.setBounds(251, 382, 65, 19);

        UsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameInputActionPerformed(evt);
            }
        });
        LogInPanel.add(UsernameInput);
        UsernameInput.setBounds(355, 341, 200, 20);
        LogInPanel.add(PasswordInput);
        PasswordInput.setBounds(355, 383, 200, 20);

        forgotPswLink.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        forgotPswLink.setForeground(new java.awt.Color(255, 0, 0));
        forgotPswLink.setText("Forgot Password ?");
        LogInPanel.add(forgotPswLink);
        forgotPswLink.setBounds(413, 516, 117, 15);

        createAccountLink.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        createAccountLink.setForeground(new java.awt.Color(255, 0, 0));
        createAccountLink.setText("Create Account");
        LogInPanel.add(createAccountLink);
        createAccountLink.setBounds(413, 495, 86, 15);

        getContentPane().add(LogInPanel);
        LogInPanel.setBounds(0, 0, 900, 610);

        RegistrationPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistrationPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        RegistrationPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        RegistrationPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        titleLabel.setText("Welcome !");
        RegistrationPanel.add(titleLabel);
        titleLabel.setBounds(322, 176, 252, 58);

        headingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headingLabel.setText("Create Account:");
        RegistrationPanel.add(headingLabel);
        headingLabel.setBounds(400, 252, 100, 17);

        userLabel.setText("Username: ");
        RegistrationPanel.add(userLabel);
        userLabel.setBounds(328, 290, 55, 14);

        passLabel.setText("Password:");
        RegistrationPanel.add(passLabel);
        passLabel.setBounds(333, 321, 50, 14);

        confirmLabel.setText("Confirm password:");
        RegistrationPanel.add(confirmLabel);
        confirmLabel.setBounds(293, 352, 90, 14);

        nameLabel.setText("Forename:");
        RegistrationPanel.add(nameLabel);
        nameLabel.setBounds(331, 383, 52, 14);

        surnameLabel.setText("Surname:");
        RegistrationPanel.add(surnameLabel);
        surnameLabel.setBounds(337, 411, 46, 14);

        emailLabel.setText("email:");
        RegistrationPanel.add(emailLabel);
        emailLabel.setBounds(355, 442, 28, 14);
        RegistrationPanel.add(usernameField);
        usernameField.setBounds(401, 287, 201, 20);

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        RegistrationPanel.add(passField);
        passField.setBounds(401, 318, 201, 20);
        RegistrationPanel.add(confirmField);
        confirmField.setBounds(401, 349, 201, 20);
        RegistrationPanel.add(forenameField);
        forenameField.setBounds(401, 380, 201, 20);
        RegistrationPanel.add(surnameField);
        surnameField.setBounds(401, 411, 201, 20);
        RegistrationPanel.add(emailField);
        emailField.setBounds(401, 442, 201, 20);

        cancelBtn.setText("Cancel");
        RegistrationPanel.add(cancelBtn);
        cancelBtn.setBounds(293, 504, 107, 23);

        createBtn.setText("Create Account");
        RegistrationPanel.add(createBtn);
        createBtn.setBounds(495, 504, 107, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pchecker/logo.png"))); // NOI18N
        RegistrationPanel.add(jLabel1);
        jLabel1.setBounds(140, 61, 602, 104);

        getContentPane().add(RegistrationPanel);
        RegistrationPanel.setBounds(0, 0, 900, 625);

        ForgotPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPasswordPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        ForgotPasswordPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        ForgotPasswordPanel.setLayout(null);

        informLabelFP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        informLabelFP.setText("Did you forget password? Do NOT worry, please insert:");
        ForgotPasswordPanel.add(informLabelFP);
        informLabelFP.setBounds(260, 320, 338, 15);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pchecker/logo.png"))); // NOI18N
        ForgotPasswordPanel.add(jLabel2);
        jLabel2.setBounds(149, 78, 602, 119);

        usernameLabelFP.setText("Username:");
        ForgotPasswordPanel.add(usernameLabelFP);
        usernameLabelFP.setBounds(320, 380, 52, 14);

        emailLabelFP.setText("email:");
        ForgotPasswordPanel.add(emailLabelFP);
        emailLabelFP.setBounds(340, 420, 28, 14);
        ForgotPasswordPanel.add(usernameFieldFP);
        usernameFieldFP.setBounds(390, 380, 180, 20);
        ForgotPasswordPanel.add(emailFieldFP);
        emailFieldFP.setBounds(390, 410, 180, 20);

        acceptBtnFP.setText("Accept");
        ForgotPasswordPanel.add(acceptBtnFP);
        acceptBtnFP.setBounds(510, 500, 86, 23);

        cancelBtnFP.setText("Cancel");
        ForgotPasswordPanel.add(cancelBtnFP);
        cancelBtnFP.setBounds(320, 500, 86, 23);

        getContentPane().add(ForgotPasswordPanel);
        ForgotPasswordPanel.setBounds(0, 0, 900, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameInputActionPerformed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ForgotPasswordPanel;
    private javax.swing.JPanel LogInPanel;
    private javax.swing.JTextField PasswordInput;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JButton acceptBtnFP;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtnFP;
    private javax.swing.JTextField confirmField;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JLabel createAccountLink;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailFieldFP;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabelFP;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField forenameField;
    private javax.swing.JLabel forgotPswLink;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel informLabelFP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usernameFieldFP;
    private javax.swing.JLabel usernameLabelFP;
    // End of variables declaration//GEN-END:variables
}
