/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pchecker;

import java.awt.Component;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Pawel Szymczyk
 */
public class LogInForm extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    public LogInForm() {
        initComponents();
        setLocationRelativeTo(null);
        RegistrationPanel.setVisible(false);
        ForgotPasswordPanel.setVisible(false);
        oldFPP.setVisible(true);
        newFPP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogInPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        UserNameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameInput = new javax.swing.JTextField();
        forgotPswLink = new javax.swing.JLabel();
        createAccountLink = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        RegistrationPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        surnameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        forenameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        confirmPassField = new javax.swing.JPasswordField();
        emailLabel1 = new javax.swing.JLabel();
        mobilNumField = new javax.swing.JTextField();
        emailLabel2 = new javax.swing.JLabel();
        DOBField = new javax.swing.JTextField();
        ForgotPasswordPanel = new javax.swing.JPanel();
        informLabelFP = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newFPP = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        oldFPP = new javax.swing.JPanel();
        usernameFieldFP = new javax.swing.JTextField();
        emailFieldFP = new javax.swing.JTextField();
        DOBinput = new javax.swing.JTextField();
        DOBLabel = new javax.swing.JLabel();
        emailLabelFP = new javax.swing.JLabel();
        usernameLabelFP = new javax.swing.JLabel();
        cancelBtnFP = new javax.swing.JButton();
        acceptBtnFP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ComPChecker");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        LogInPanel.setBackground(new java.awt.Color(255, 255, 255));
        LogInPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        LogInPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        LogInPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        LogInPanel.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pchecker/logo.png"))); // NOI18N
        LogInPanel.add(logo);
        logo.setBounds(140, 150, 602, 119);

        loginBtn.setBackground(new java.awt.Color(127, 127, 127));
        loginBtn.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        LogInPanel.add(loginBtn);
        loginBtn.setBounds(370, 430, 71, 45);

        exitBtn.setBackground(new java.awt.Color(127, 127, 127));
        exitBtn.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        LogInPanel.add(exitBtn);
        exitBtn.setBounds(470, 430, 70, 45);

        UserNameLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        UserNameLabel.setText("Username:");
        LogInPanel.add(UserNameLabel);
        UserNameLabel.setBounds(250, 340, 100, 30);

        PasswordLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        PasswordLabel.setText("Password:");
        LogInPanel.add(PasswordLabel);
        PasswordLabel.setBounds(250, 380, 100, 30);

        UsernameInput.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        UsernameInput.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        UsernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameInputActionPerformed(evt);
            }
        });
        LogInPanel.add(UsernameInput);
        UsernameInput.setBounds(350, 340, 210, 30);

        forgotPswLink.setFont(new java.awt.Font("Kalinga", 2, 12)); // NOI18N
        forgotPswLink.setForeground(new java.awt.Color(179, 0, 0));
        forgotPswLink.setText("Forgot Password ?");
        forgotPswLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPswLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPswLinkMouseClicked(evt);
            }
        });
        LogInPanel.add(forgotPswLink);
        forgotPswLink.setBounds(410, 520, 117, 20);

        createAccountLink.setFont(new java.awt.Font("Kalinga", 2, 12)); // NOI18N
        createAccountLink.setForeground(new java.awt.Color(179, 0, 0));
        createAccountLink.setText("Create Account");
        createAccountLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountLinkMouseClicked(evt);
            }
        });
        LogInPanel.add(createAccountLink);
        createAccountLink.setBounds(410, 500, 100, 20);

        PasswordInput.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        PasswordInput.setToolTipText("");
        PasswordInput.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        PasswordInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordInputActionPerformed(evt);
            }
        });
        LogInPanel.add(PasswordInput);
        PasswordInput.setBounds(350, 380, 210, 30);

        getContentPane().add(LogInPanel);
        LogInPanel.setBounds(0, 0, 900, 600);

        RegistrationPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegistrationPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        RegistrationPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        RegistrationPanel.setLayout(null);

        titleLabel.setFont(new java.awt.Font("Kalinga", 1, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(127, 127, 127));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Welcome !");
        RegistrationPanel.add(titleLabel);
        titleLabel.setBounds(330, 130, 280, 70);

        headingLabel.setFont(new java.awt.Font("Kalinga", 1, 20)); // NOI18N
        headingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLabel.setText("Create Account:");
        RegistrationPanel.add(headingLabel);
        headingLabel.setBounds(390, 210, 160, 22);

        userLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        userLabel.setText("Username: ");
        RegistrationPanel.add(userLabel);
        userLabel.setBounds(280, 240, 90, 30);

        passLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        passLabel.setText("Password:");
        RegistrationPanel.add(passLabel);
        passLabel.setBounds(280, 280, 90, 30);

        confirmLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        confirmLabel.setText("Confirm password: ");
        RegistrationPanel.add(confirmLabel);
        confirmLabel.setBounds(220, 320, 150, 30);

        nameLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        nameLabel.setText("Forename:");
        RegistrationPanel.add(nameLabel);
        nameLabel.setBounds(280, 360, 90, 30);

        surnameLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        surnameLabel.setText("Surname:");
        RegistrationPanel.add(surnameLabel);
        surnameLabel.setBounds(290, 400, 80, 30);

        emailLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        emailLabel.setText("email:");
        RegistrationPanel.add(emailLabel);
        emailLabel.setBounds(310, 440, 60, 30);

        usernameField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        usernameField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        RegistrationPanel.add(usernameField);
        usernameField.setBounds(370, 240, 210, 30);

        forenameField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        forenameField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        RegistrationPanel.add(forenameField);
        forenameField.setBounds(370, 360, 210, 30);

        surnameField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        surnameField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        RegistrationPanel.add(surnameField);
        surnameField.setBounds(370, 400, 210, 30);

        emailField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        emailField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        RegistrationPanel.add(emailField);
        emailField.setBounds(370, 440, 210, 30);

        cancelBtn.setBackground(new java.awt.Color(127, 127, 127));
        cancelBtn.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        RegistrationPanel.add(cancelBtn);
        cancelBtn.setBounds(720, 510, 140, 40);

        createBtn.setBackground(new java.awt.Color(127, 127, 127));
        createBtn.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        createBtn.setForeground(new java.awt.Color(255, 255, 255));
        createBtn.setText("Create Account");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        RegistrationPanel.add(createBtn);
        createBtn.setBounds(720, 460, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pchecker/logo.png"))); // NOI18N
        RegistrationPanel.add(jLabel1);
        jLabel1.setBounds(140, 10, 602, 110);

        passField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        passField.setToolTipText("");
        passField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        RegistrationPanel.add(passField);
        passField.setBounds(370, 280, 210, 30);

        confirmPassField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        confirmPassField.setToolTipText("");
        confirmPassField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        confirmPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassFieldActionPerformed(evt);
            }
        });
        RegistrationPanel.add(confirmPassField);
        confirmPassField.setBounds(370, 320, 210, 30);

        emailLabel1.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        emailLabel1.setText("Mobile No.");
        RegistrationPanel.add(emailLabel1);
        emailLabel1.setBounds(280, 480, 90, 30);

        mobilNumField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        mobilNumField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        RegistrationPanel.add(mobilNumField);
        mobilNumField.setBounds(370, 480, 210, 30);

        emailLabel2.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        emailLabel2.setText("Date of birth (dd/mm/yyyy)");
        RegistrationPanel.add(emailLabel2);
        emailLabel2.setBounds(170, 520, 200, 30);

        DOBField.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        DOBField.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        RegistrationPanel.add(DOBField);
        DOBField.setBounds(370, 520, 210, 30);

        getContentPane().add(RegistrationPanel);
        RegistrationPanel.setBounds(0, 0, 900, 600);

        ForgotPasswordPanel.setBackground(new java.awt.Color(255, 255, 255));
        ForgotPasswordPanel.setMaximumSize(new java.awt.Dimension(900, 600));
        ForgotPasswordPanel.setMinimumSize(new java.awt.Dimension(900, 600));
        ForgotPasswordPanel.setLayout(null);

        informLabelFP.setFont(new java.awt.Font("Kalinga", 1, 20)); // NOI18N
        informLabelFP.setForeground(new java.awt.Color(127, 127, 127));
        informLabelFP.setText("Did you forget password? Do NOT worry, please insert:");
        ForgotPasswordPanel.add(informLabelFP);
        informLabelFP.setBounds(180, 190, 560, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pchecker/logo.png"))); // NOI18N
        ForgotPasswordPanel.add(jLabel2);
        jLabel2.setBounds(150, 30, 602, 119);

        newFPP.setBackground(new java.awt.Color(255, 255, 255));
        newFPP.setMaximumSize(new java.awt.Dimension(860, 300));
        newFPP.setMinimumSize(new java.awt.Dimension(860, 300));
        newFPP.setPreferredSize(new java.awt.Dimension(860, 300));
        newFPP.setLayout(null);

        jPasswordField1.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        newFPP.add(jPasswordField1);
        jPasswordField1.setBounds(410, 80, 180, 30);

        jPasswordField2.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jPasswordField2.setText("jPasswordField2");
        jPasswordField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        newFPP.add(jPasswordField2);
        jPasswordField2.setBounds(410, 130, 180, 30);

        jLabel3.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        jLabel3.setText("New Password:");
        newFPP.add(jLabel3);
        jLabel3.setBounds(280, 80, 130, 30);

        jLabel4.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        jLabel4.setText("Confirm Password:");
        newFPP.add(jLabel4);
        jLabel4.setBounds(260, 130, 150, 30);

        jButton1.setBackground(new java.awt.Color(127, 127, 127));
        jButton1.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Accept");
        newFPP.add(jButton1);
        jButton1.setBounds(460, 220, 90, 40);

        jButton2.setBackground(new java.awt.Color(127, 127, 127));
        jButton2.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        newFPP.add(jButton2);
        jButton2.setBounds(270, 220, 90, 40);

        ForgotPasswordPanel.add(newFPP);
        newFPP.setBounds(30, 240, 840, 300);

        oldFPP.setBackground(new java.awt.Color(255, 255, 255));
        oldFPP.setMaximumSize(new java.awt.Dimension(860, 300));
        oldFPP.setLayout(null);

        usernameFieldFP.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        usernameFieldFP.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        oldFPP.add(usernameFieldFP);
        usernameFieldFP.setBounds(440, 70, 180, 30);

        emailFieldFP.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        emailFieldFP.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        oldFPP.add(emailFieldFP);
        emailFieldFP.setBounds(440, 110, 180, 30);

        DOBinput.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        DOBinput.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(179, 0, 0)));
        oldFPP.add(DOBinput);
        DOBinput.setBounds(440, 150, 180, 30);

        DOBLabel.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        DOBLabel.setText("Day of Birth (DD/MM/YYYY):");
        oldFPP.add(DOBLabel);
        DOBLabel.setBounds(230, 150, 210, 30);

        emailLabelFP.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        emailLabelFP.setText("email:");
        oldFPP.add(emailLabelFP);
        emailLabelFP.setBounds(380, 110, 60, 30);

        usernameLabelFP.setFont(new java.awt.Font("Kalinga", 0, 15)); // NOI18N
        usernameLabelFP.setText("Username:");
        oldFPP.add(usernameLabelFP);
        usernameLabelFP.setBounds(350, 70, 90, 30);

        cancelBtnFP.setBackground(new java.awt.Color(127, 127, 127));
        cancelBtnFP.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        cancelBtnFP.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtnFP.setText("Cancel");
        cancelBtnFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnFPActionPerformed(evt);
            }
        });
        oldFPP.add(cancelBtnFP);
        cancelBtnFP.setBounds(300, 230, 90, 40);

        acceptBtnFP.setBackground(new java.awt.Color(127, 127, 127));
        acceptBtnFP.setFont(new java.awt.Font("Kalinga", 1, 14)); // NOI18N
        acceptBtnFP.setForeground(new java.awt.Color(255, 255, 255));
        acceptBtnFP.setText("Accept");
        acceptBtnFP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnFPActionPerformed(evt);
            }
        });
        oldFPP.add(acceptBtnFP);
        acceptBtnFP.setBounds(490, 230, 90, 40);

        ForgotPasswordPanel.add(oldFPP);
        oldFPP.setBounds(0, 230, 900, 350);

        getContentPane().add(ForgotPasswordPanel);
        ForgotPasswordPanel.setBounds(0, 0, 900, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameInputActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        login();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void PasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordInputActionPerformed

    private void createAccountLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountLinkMouseClicked
        
        
            LogInPanel.setVisible(false);
            RegistrationPanel.setVisible(true);
            
        
                              
        
        
    }//GEN-LAST:event_createAccountLinkMouseClicked

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void confirmPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPassFieldActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        
        String username = usernameField.getText();
        String password = String.valueOf(passField.getPassword());
        String passwordConfirm = String.valueOf(confirmPassField.getPassword());

        String name = forenameField.getText();
        String surname = surnameField.getText();
        String email = emailField.getText();
        String DOB = DOBField.getText();
        
        String mobilNumber = mobilNumField.getText();
        //Integer mobilNumber = Integer.parseInt(mobilNumField.getText());
        
        int emailValidation = email.indexOf('@');

        
        boolean confirm = true;
        
        if(username.isEmpty()|| password.isEmpty() || passwordConfirm.isEmpty() || name.isEmpty() || surname.isEmpty() || email.isEmpty()|| DOB.isEmpty() || mobilNumber.isEmpty()){
          
        confirm = false;
        
        }
        
        // validation process, sets lenths and types needed to validate form
        if (confirm) { //Checks to see all fields are complete.
            if (emailValidation >= 0) {
              
                if (surname.length() <= 45) {
                    if (name.length() <= 45) {
                        if(DOB.length() >= 10 && DOB.length() <= 10){
                            if(mobilNumber.length()>=11 && mobilNumber.length()<=11){
                            if(password.equals(passwordConfirm)){
                                
                            
                        userAdminAccount user = new userAdminAccount();
                        boolean result = user.usernameAvailability(username);
                        if (result) {
                            
                            user.setUsername(username);                        
                            user.setPassword(password);
                            user.setFname(name);
                            user.setSname(surname);
                            user.setEmail(email);
                            user.setDOB(DOB);     
                            user.setMobil(mobilNumber); 
                            user.setType(false);
                            
                            user.saveUser();
                            
                            //if valid the account is created in database 
                            JOptionPane.showMessageDialog(null, "Account Created. You will be returned to the Log In Page", "Account Created", JOptionPane.INFORMATION_MESSAGE);
                            LogInForm frm = new LogInForm();
                            this.setVisible(false);
                            frm.setVisible(true);

                        }else{ //error messages for validation
                         JOptionPane.showMessageDialog(null, "Account in use, ","", JOptionPane.INFORMATION_MESSAGE);
                        
                        }
                        } else {
                        JOptionPane.showMessageDialog(null, "Passwords dont match", "", JOptionPane.INFORMATION_MESSAGE);

                    }
                            } else {
                        JOptionPane.showMessageDialog(null, "Invaild Mobile Number", "", JOptionPane.INFORMATION_MESSAGE);

                    }
                    } else {
                        JOptionPane.showMessageDialog(null, "Invaid Date of Birth", "", JOptionPane.INFORMATION_MESSAGE);

                    }

                    } else {
                        JOptionPane.showMessageDialog(null, "Name too long.", "", JOptionPane.INFORMATION_MESSAGE);

                    }

                } else {

                    JOptionPane.showMessageDialog(null, "Surname too long.", "", JOptionPane.INFORMATION_MESSAGE);

                }

            } else {
                JOptionPane.showMessageDialog(null, "Email Issue: Please ensure the email field contains an '@'.", "Email Issue", JOptionPane.INFORMATION_MESSAGE);

            }

        } else {

            JOptionPane.showMessageDialog(null, "Please complete all fields!", "Complete All fields", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_createBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        LogInPanel.setVisible(true);
        RegistrationPanel.setVisible(false);
        
        cleanInput(RegistrationPanel);
    
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * This code reset input in "Create Account", after Cancel form.
     * @param panel 
     */
    private void cleanInput(JPanel panel) {
        for (Component c : panel.getComponents())
        {
            if (c instanceof JTextField)
            {
                JTextField j = (JTextField)c;
                j.setText("");
            }
        }
    }
    
    private void forgotPswLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPswLinkMouseClicked
       LogInPanel.setVisible(false);
       ForgotPasswordPanel.setVisible(true);
    }//GEN-LAST:event_forgotPswLinkMouseClicked

    private void cancelBtnFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnFPActionPerformed
        LogInPanel.setVisible(true);
        ForgotPasswordPanel.setVisible(false);
        
        cleanInput(oldFPP);
    }//GEN-LAST:event_cancelBtnFPActionPerformed

    private void acceptBtnFPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBtnFPActionPerformed
        oldFPP.setVisible(false);
        newFPP.setVisible(true);
    }//GEN-LAST:event_acceptBtnFPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        newFPP.setVisible(false);
        oldFPP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void login() {

        String username = UsernameInput.getText();
        String password = String.valueOf(PasswordInput.getPassword());
        
//create new user account
        userAdminAccount user = new userAdminAccount();
          

        boolean successful = user.checkPassword(username, password);
        if (successful) {
            
            user.LogInService(username, password); //asks for username and password

            AdminUserFrame frm = new AdminUserFrame(user); //opens general user form
            this.setVisible(false);
            frm.setVisible(true);

          
        } else { //error message prompted
            JOptionPane.showMessageDialog(null, "User account can not be found. Please try again or create a new account", "No Account Found", JOptionPane.INFORMATION_MESSAGE);
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
                ServerControl.connect(); //Connect to VM via ssh Tunnel 

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOBField;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JTextField DOBinput;
    private javax.swing.JPanel ForgotPasswordPanel;
    private javax.swing.JPanel LogInPanel;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JButton acceptBtnFP;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtnFP;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPasswordField confirmPassField;
    private javax.swing.JLabel createAccountLink;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailFieldFP;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel emailLabelFP;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField forenameField;
    private javax.swing.JLabel forgotPswLink;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel informLabelFP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField mobilNumField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel newFPP;
    private javax.swing.JPanel oldFPP;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usernameFieldFP;
    private javax.swing.JLabel usernameLabelFP;
    // End of variables declaration//GEN-END:variables
}
